#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_OOP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLThuvien")]
	public partial class QLThuvien1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMuonQuaHan(MuonQuaHan instance);
    partial void UpdateMuonQuaHan(MuonQuaHan instance);
    partial void DeleteMuonQuaHan(MuonQuaHan instance);
    partial void InsertNhaXuatBan(NhaXuatBan instance);
    partial void UpdateNhaXuatBan(NhaXuatBan instance);
    partial void DeleteNhaXuatBan(NhaXuatBan instance);
    partial void InsertPhieuMuon(PhieuMuon instance);
    partial void UpdatePhieuMuon(PhieuMuon instance);
    partial void DeletePhieuMuon(PhieuMuon instance);
    partial void InsertTheLoai(TheLoai instance);
    partial void UpdateTheLoai(TheLoai instance);
    partial void DeleteTheLoai(TheLoai instance);
    partial void InsertThongTinSach(ThongTinSach instance);
    partial void UpdateThongTinSach(ThongTinSach instance);
    partial void DeleteThongTinSach(ThongTinSach instance);
    partial void InsertDocGia(DocGia instance);
    partial void UpdateDocGia(DocGia instance);
    partial void DeleteDocGia(DocGia instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public QLThuvien1DataContext() : 
				base(global::DoAn_OOP.Properties.Settings.Default.QLThuvienConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuvien1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuvien1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuvien1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuvien1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MuonQuaHan> MuonQuaHans
		{
			get
			{
				return this.GetTable<MuonQuaHan>();
			}
		}
		
		public System.Data.Linq.Table<NhaXuatBan> NhaXuatBans
		{
			get
			{
				return this.GetTable<NhaXuatBan>();
			}
		}
		
		public System.Data.Linq.Table<PhieuMuon> PhieuMuons
		{
			get
			{
				return this.GetTable<PhieuMuon>();
			}
		}
		
		public System.Data.Linq.Table<TheLoai> TheLoais
		{
			get
			{
				return this.GetTable<TheLoai>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinSach> ThongTinSaches
		{
			get
			{
				return this.GetTable<ThongTinSach>();
			}
		}
		
		public System.Data.Linq.Table<DocGia> DocGias
		{
			get
			{
				return this.GetTable<DocGia>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MuonQuaHan")]
	public partial class MuonQuaHan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDDocGia;
		
		private string _IDSach;
		
		private string _NgayTra;
		
		private int _SoNgayQuaHan;
		
		private string _TienPhaiTra;
		
		private EntityRef<DocGia> _DocGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDocGiaChanging(string value);
    partial void OnIDDocGiaChanged();
    partial void OnIDSachChanging(string value);
    partial void OnIDSachChanged();
    partial void OnNgayTraChanging(string value);
    partial void OnNgayTraChanged();
    partial void OnSoNgayQuaHanChanging(int value);
    partial void OnSoNgayQuaHanChanged();
    partial void OnTienPhaiTraChanging(string value);
    partial void OnTienPhaiTraChanged();
    #endregion
		
		public MuonQuaHan()
		{
			this._DocGia = default(EntityRef<DocGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDocGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDDocGia
		{
			get
			{
				return this._IDDocGia;
			}
			set
			{
				if ((this._IDDocGia != value))
				{
					if (this._DocGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDocGiaChanging(value);
					this.SendPropertyChanging();
					this._IDDocGia = value;
					this.SendPropertyChanged("IDDocGia");
					this.OnIDDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSach", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDSach
		{
			get
			{
				return this._IDSach;
			}
			set
			{
				if ((this._IDSach != value))
				{
					this.OnIDSachChanging(value);
					this.SendPropertyChanging();
					this._IDSach = value;
					this.SendPropertyChanged("IDSach");
					this.OnIDSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this.OnNgayTraChanging(value);
					this.SendPropertyChanging();
					this._NgayTra = value;
					this.SendPropertyChanged("NgayTra");
					this.OnNgayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgayQuaHan", DbType="Int NOT NULL")]
		public int SoNgayQuaHan
		{
			get
			{
				return this._SoNgayQuaHan;
			}
			set
			{
				if ((this._SoNgayQuaHan != value))
				{
					this.OnSoNgayQuaHanChanging(value);
					this.SendPropertyChanging();
					this._SoNgayQuaHan = value;
					this.SendPropertyChanged("SoNgayQuaHan");
					this.OnSoNgayQuaHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienPhaiTra", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TienPhaiTra
		{
			get
			{
				return this._TienPhaiTra;
			}
			set
			{
				if ((this._TienPhaiTra != value))
				{
					this.OnTienPhaiTraChanging(value);
					this.SendPropertyChanging();
					this._TienPhaiTra = value;
					this.SendPropertyChanged("TienPhaiTra");
					this.OnTienPhaiTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DocGia_MuonQuaHan", Storage="_DocGia", ThisKey="IDDocGia", OtherKey="IDDocGia", IsForeignKey=true)]
		public DocGia DocGia
		{
			get
			{
				return this._DocGia.Entity;
			}
			set
			{
				DocGia previousValue = this._DocGia.Entity;
				if (((previousValue != value) 
							|| (this._DocGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DocGia.Entity = null;
						previousValue.MuonQuaHans.Remove(this);
					}
					this._DocGia.Entity = value;
					if ((value != null))
					{
						value.MuonQuaHans.Add(this);
						this._IDDocGia = value.IDDocGia;
					}
					else
					{
						this._IDDocGia = default(string);
					}
					this.SendPropertyChanged("DocGia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaXuatBan")]
	public partial class NhaXuatBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDNhaXuatBan;
		
		private string _TenNhaXuatBan;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private EntitySet<ThongTinSach> _ThongTinSaches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDNhaXuatBanChanging(string value);
    partial void OnIDNhaXuatBanChanged();
    partial void OnTenNhaXuatBanChanging(string value);
    partial void OnTenNhaXuatBanChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public NhaXuatBan()
		{
			this._ThongTinSaches = new EntitySet<ThongTinSach>(new Action<ThongTinSach>(this.attach_ThongTinSaches), new Action<ThongTinSach>(this.detach_ThongTinSaches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNhaXuatBan", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDNhaXuatBan
		{
			get
			{
				return this._IDNhaXuatBan;
			}
			set
			{
				if ((this._IDNhaXuatBan != value))
				{
					this.OnIDNhaXuatBanChanging(value);
					this.SendPropertyChanging();
					this._IDNhaXuatBan = value;
					this.SendPropertyChanged("IDNhaXuatBan");
					this.OnIDNhaXuatBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhaXuatBan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNhaXuatBan
		{
			get
			{
				return this._TenNhaXuatBan;
			}
			set
			{
				if ((this._TenNhaXuatBan != value))
				{
					this.OnTenNhaXuatBanChanging(value);
					this.SendPropertyChanging();
					this._TenNhaXuatBan = value;
					this.SendPropertyChanged("TenNhaXuatBan");
					this.OnTenNhaXuatBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaXuatBan_ThongTinSach", Storage="_ThongTinSaches", ThisKey="IDNhaXuatBan", OtherKey="NhaXuatBan")]
		public EntitySet<ThongTinSach> ThongTinSaches
		{
			get
			{
				return this._ThongTinSaches;
			}
			set
			{
				this._ThongTinSaches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThongTinSaches(ThongTinSach entity)
		{
			this.SendPropertyChanging();
			entity.NhaXuatBan1 = this;
		}
		
		private void detach_ThongTinSaches(ThongTinSach entity)
		{
			this.SendPropertyChanging();
			entity.NhaXuatBan1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuMuon")]
	public partial class PhieuMuon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDDocGia;
		
		private string _IDSach;
		
		private System.Nullable<System.DateTime> _NgayMuon;
		
		private System.Nullable<System.DateTime> _NgayTra;
		
		private System.Nullable<int> _SoLuong;
		
		private EntityRef<ThongTinSach> _ThongTinSach;
		
		private EntityRef<DocGia> _DocGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDocGiaChanging(string value);
    partial void OnIDDocGiaChanged();
    partial void OnIDSachChanging(string value);
    partial void OnIDSachChanged();
    partial void OnNgayMuonChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayMuonChanged();
    partial void OnNgayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public PhieuMuon()
		{
			this._ThongTinSach = default(EntityRef<ThongTinSach>);
			this._DocGia = default(EntityRef<DocGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDocGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDDocGia
		{
			get
			{
				return this._IDDocGia;
			}
			set
			{
				if ((this._IDDocGia != value))
				{
					if (this._DocGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDocGiaChanging(value);
					this.SendPropertyChanging();
					this._IDDocGia = value;
					this.SendPropertyChanged("IDDocGia");
					this.OnIDDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSach", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDSach
		{
			get
			{
				return this._IDSach;
			}
			set
			{
				if ((this._IDSach != value))
				{
					if (this._ThongTinSach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDSachChanging(value);
					this.SendPropertyChanging();
					this._IDSach = value;
					this.SendPropertyChanged("IDSach");
					this.OnIDSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="Date")]
		public System.Nullable<System.DateTime> NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this.OnNgayMuonChanging(value);
					this.SendPropertyChanging();
					this._NgayMuon = value;
					this.SendPropertyChanged("NgayMuon");
					this.OnNgayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this.OnNgayTraChanging(value);
					this.SendPropertyChanging();
					this._NgayTra = value;
					this.SendPropertyChanged("NgayTra");
					this.OnNgayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinSach_PhieuMuon", Storage="_ThongTinSach", ThisKey="IDSach", OtherKey="IDSach", IsForeignKey=true)]
		public ThongTinSach ThongTinSach
		{
			get
			{
				return this._ThongTinSach.Entity;
			}
			set
			{
				ThongTinSach previousValue = this._ThongTinSach.Entity;
				if (((previousValue != value) 
							|| (this._ThongTinSach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThongTinSach.Entity = null;
						previousValue.PhieuMuons.Remove(this);
					}
					this._ThongTinSach.Entity = value;
					if ((value != null))
					{
						value.PhieuMuons.Add(this);
						this._IDSach = value.IDSach;
					}
					else
					{
						this._IDSach = default(string);
					}
					this.SendPropertyChanged("ThongTinSach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DocGia_PhieuMuon", Storage="_DocGia", ThisKey="IDDocGia", OtherKey="IDDocGia", IsForeignKey=true)]
		public DocGia DocGia
		{
			get
			{
				return this._DocGia.Entity;
			}
			set
			{
				DocGia previousValue = this._DocGia.Entity;
				if (((previousValue != value) 
							|| (this._DocGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DocGia.Entity = null;
						previousValue.PhieuMuons.Remove(this);
					}
					this._DocGia.Entity = value;
					if ((value != null))
					{
						value.PhieuMuons.Add(this);
						this._IDDocGia = value.IDDocGia;
					}
					else
					{
						this._IDDocGia = default(string);
					}
					this.SendPropertyChanged("DocGia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheLoai")]
	public partial class TheLoai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDTheLoai;
		
		private string _TenTheLoai;
		
		private EntitySet<ThongTinSach> _ThongTinSaches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTheLoaiChanging(string value);
    partial void OnIDTheLoaiChanged();
    partial void OnTenTheLoaiChanging(string value);
    partial void OnTenTheLoaiChanged();
    #endregion
		
		public TheLoai()
		{
			this._ThongTinSaches = new EntitySet<ThongTinSach>(new Action<ThongTinSach>(this.attach_ThongTinSaches), new Action<ThongTinSach>(this.detach_ThongTinSaches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTheLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDTheLoai
		{
			get
			{
				return this._IDTheLoai;
			}
			set
			{
				if ((this._IDTheLoai != value))
				{
					this.OnIDTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._IDTheLoai = value;
					this.SendPropertyChanged("IDTheLoai");
					this.OnIDTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTheLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenTheLoai
		{
			get
			{
				return this._TenTheLoai;
			}
			set
			{
				if ((this._TenTheLoai != value))
				{
					this.OnTenTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenTheLoai = value;
					this.SendPropertyChanged("TenTheLoai");
					this.OnTenTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheLoai_ThongTinSach", Storage="_ThongTinSaches", ThisKey="IDTheLoai", OtherKey="IDTheLoai")]
		public EntitySet<ThongTinSach> ThongTinSaches
		{
			get
			{
				return this._ThongTinSaches;
			}
			set
			{
				this._ThongTinSaches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThongTinSaches(ThongTinSach entity)
		{
			this.SendPropertyChanging();
			entity.TheLoai = this;
		}
		
		private void detach_ThongTinSaches(ThongTinSach entity)
		{
			this.SendPropertyChanging();
			entity.TheLoai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinSach")]
	public partial class ThongTinSach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDTheLoai;
		
		private string _IDSach;
		
		private string _TenSach;
		
		private string _NhaXuatBan;
		
		private System.Nullable<System.DateTime> _NgayNhapKho;
		
		private string _Gia;
		
		private System.Nullable<int> _TonKho;
		
		private EntitySet<PhieuMuon> _PhieuMuons;
		
		private EntityRef<NhaXuatBan> _NhaXuatBan1;
		
		private EntityRef<TheLoai> _TheLoai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTheLoaiChanging(string value);
    partial void OnIDTheLoaiChanged();
    partial void OnIDSachChanging(string value);
    partial void OnIDSachChanged();
    partial void OnTenSachChanging(string value);
    partial void OnTenSachChanged();
    partial void OnNhaXuatBanChanging(string value);
    partial void OnNhaXuatBanChanged();
    partial void OnNgayNhapKhoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapKhoChanged();
    partial void OnGiaChanging(string value);
    partial void OnGiaChanged();
    partial void OnTonKhoChanging(System.Nullable<int> value);
    partial void OnTonKhoChanged();
    #endregion
		
		public ThongTinSach()
		{
			this._PhieuMuons = new EntitySet<PhieuMuon>(new Action<PhieuMuon>(this.attach_PhieuMuons), new Action<PhieuMuon>(this.detach_PhieuMuons));
			this._NhaXuatBan1 = default(EntityRef<NhaXuatBan>);
			this._TheLoai = default(EntityRef<TheLoai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTheLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IDTheLoai
		{
			get
			{
				return this._IDTheLoai;
			}
			set
			{
				if ((this._IDTheLoai != value))
				{
					if (this._TheLoai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._IDTheLoai = value;
					this.SendPropertyChanged("IDTheLoai");
					this.OnIDTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSach", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDSach
		{
			get
			{
				return this._IDSach;
			}
			set
			{
				if ((this._IDSach != value))
				{
					this.OnIDSachChanging(value);
					this.SendPropertyChanging();
					this._IDSach = value;
					this.SendPropertyChanged("IDSach");
					this.OnIDSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this.OnTenSachChanging(value);
					this.SendPropertyChanging();
					this._TenSach = value;
					this.SendPropertyChanged("TenSach");
					this.OnTenSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhaXuatBan", DbType="NVarChar(50)")]
		public string NhaXuatBan
		{
			get
			{
				return this._NhaXuatBan;
			}
			set
			{
				if ((this._NhaXuatBan != value))
				{
					if (this._NhaXuatBan1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNhaXuatBanChanging(value);
					this.SendPropertyChanging();
					this._NhaXuatBan = value;
					this.SendPropertyChanged("NhaXuatBan");
					this.OnNhaXuatBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhapKho", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNhapKho
		{
			get
			{
				return this._NgayNhapKho;
			}
			set
			{
				if ((this._NgayNhapKho != value))
				{
					this.OnNgayNhapKhoChanging(value);
					this.SendPropertyChanging();
					this._NgayNhapKho = value;
					this.SendPropertyChanged("NgayNhapKho");
					this.OnNgayNhapKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TonKho", DbType="Int")]
		public System.Nullable<int> TonKho
		{
			get
			{
				return this._TonKho;
			}
			set
			{
				if ((this._TonKho != value))
				{
					this.OnTonKhoChanging(value);
					this.SendPropertyChanging();
					this._TonKho = value;
					this.SendPropertyChanged("TonKho");
					this.OnTonKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThongTinSach_PhieuMuon", Storage="_PhieuMuons", ThisKey="IDSach", OtherKey="IDSach")]
		public EntitySet<PhieuMuon> PhieuMuons
		{
			get
			{
				return this._PhieuMuons;
			}
			set
			{
				this._PhieuMuons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaXuatBan_ThongTinSach", Storage="_NhaXuatBan1", ThisKey="NhaXuatBan", OtherKey="IDNhaXuatBan", IsForeignKey=true)]
		public NhaXuatBan NhaXuatBan1
		{
			get
			{
				return this._NhaXuatBan1.Entity;
			}
			set
			{
				NhaXuatBan previousValue = this._NhaXuatBan1.Entity;
				if (((previousValue != value) 
							|| (this._NhaXuatBan1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaXuatBan1.Entity = null;
						previousValue.ThongTinSaches.Remove(this);
					}
					this._NhaXuatBan1.Entity = value;
					if ((value != null))
					{
						value.ThongTinSaches.Add(this);
						this._NhaXuatBan = value.IDNhaXuatBan;
					}
					else
					{
						this._NhaXuatBan = default(string);
					}
					this.SendPropertyChanged("NhaXuatBan1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheLoai_ThongTinSach", Storage="_TheLoai", ThisKey="IDTheLoai", OtherKey="IDTheLoai", IsForeignKey=true)]
		public TheLoai TheLoai
		{
			get
			{
				return this._TheLoai.Entity;
			}
			set
			{
				TheLoai previousValue = this._TheLoai.Entity;
				if (((previousValue != value) 
							|| (this._TheLoai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheLoai.Entity = null;
						previousValue.ThongTinSaches.Remove(this);
					}
					this._TheLoai.Entity = value;
					if ((value != null))
					{
						value.ThongTinSaches.Add(this);
						this._IDTheLoai = value.IDTheLoai;
					}
					else
					{
						this._IDTheLoai = default(string);
					}
					this.SendPropertyChanged("TheLoai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuMuons(PhieuMuon entity)
		{
			this.SendPropertyChanging();
			entity.ThongTinSach = this;
		}
		
		private void detach_PhieuMuons(PhieuMuon entity)
		{
			this.SendPropertyChanging();
			entity.ThongTinSach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocGia")]
	public partial class DocGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDDocGia;
		
		private string _HoTen;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private System.Data.Linq.Binary _HinhAnh;
		
		private EntitySet<MuonQuaHan> _MuonQuaHans;
		
		private EntitySet<PhieuMuon> _PhieuMuons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDocGiaChanging(string value);
    partial void OnIDDocGiaChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnHinhAnhChanging(System.Data.Linq.Binary value);
    partial void OnHinhAnhChanged();
    #endregion
		
		public DocGia()
		{
			this._MuonQuaHans = new EntitySet<MuonQuaHan>(new Action<MuonQuaHan>(this.attach_MuonQuaHans), new Action<MuonQuaHan>(this.detach_MuonQuaHans));
			this._PhieuMuons = new EntitySet<PhieuMuon>(new Action<PhieuMuon>(this.attach_PhieuMuons), new Action<PhieuMuon>(this.detach_PhieuMuons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDocGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDDocGia
		{
			get
			{
				return this._IDDocGia;
			}
			set
			{
				if ((this._IDDocGia != value))
				{
					this.OnIDDocGiaChanging(value);
					this.SendPropertyChanging();
					this._IDDocGia = value;
					this.SendPropertyChanged("IDDocGia");
					this.OnIDDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DocGia_MuonQuaHan", Storage="_MuonQuaHans", ThisKey="IDDocGia", OtherKey="IDDocGia")]
		public EntitySet<MuonQuaHan> MuonQuaHans
		{
			get
			{
				return this._MuonQuaHans;
			}
			set
			{
				this._MuonQuaHans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DocGia_PhieuMuon", Storage="_PhieuMuons", ThisKey="IDDocGia", OtherKey="IDDocGia")]
		public EntitySet<PhieuMuon> PhieuMuons
		{
			get
			{
				return this._PhieuMuons;
			}
			set
			{
				this._PhieuMuons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MuonQuaHans(MuonQuaHan entity)
		{
			this.SendPropertyChanging();
			entity.DocGia = this;
		}
		
		private void detach_MuonQuaHans(MuonQuaHan entity)
		{
			this.SendPropertyChanging();
			entity.DocGia = null;
		}
		
		private void attach_PhieuMuons(PhieuMuon entity)
		{
			this.SendPropertyChanging();
			entity.DocGia = this;
		}
		
		private void detach_PhieuMuons(PhieuMuon entity)
		{
			this.SendPropertyChanging();
			entity.DocGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan1;
		
		private string _MatKhau;
		
		private string _PhanQuyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoan1Changing(string value);
    partial void OnTaiKhoan1Changed();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnPhanQuyenChanging(string value);
    partial void OnPhanQuyenChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TaiKhoan", Storage="_TaiKhoan1", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan1
		{
			get
			{
				return this._TaiKhoan1;
			}
			set
			{
				if ((this._TaiKhoan1 != value))
				{
					this.OnTaiKhoan1Changing(value);
					this.SendPropertyChanging();
					this._TaiKhoan1 = value;
					this.SendPropertyChanged("TaiKhoan1");
					this.OnTaiKhoan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanQuyen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PhanQuyen
		{
			get
			{
				return this._PhanQuyen;
			}
			set
			{
				if ((this._PhanQuyen != value))
				{
					this.OnPhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._PhanQuyen = value;
					this.SendPropertyChanged("PhanQuyen");
					this.OnPhanQuyenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
